# Generated by Django 3.2.6 on 2021-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.TextField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
